const actions = {
    SET_PICKUP_LOCATION: 'SET_PICKUP_LOCATION',
    SET_DROP_LOCATION: 'SET_DROP_LOCATION',
    SET_ACCOUNT: 'SET_ACCOUNT',
    SET_RIDE_BALANCE: 'SET_RIDE_BALANCE',
};

export default actions;